namespace BillLading.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class CreateLading1 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Ladings", "PlaceOfIssue2", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "DateOfIssue3", c => c.DateTime(nullable: false));
            AddColumn("dbo.Ladings", "Sender4", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "SenderAddress4", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "SenderPhone4", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "Receiver5", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "ReceiverAddress5", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "ReceiverPhone5", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "Carrier6", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "CarrierAddress6", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "CarrierPhone6", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "Forwarder7", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "ForwarderAddress7", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "ForwarderPhone7", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "TakingOverGoodsPlace8", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "TakingOverGoodsDate8", c => c.DateTime(nullable: false));
            AddColumn("dbo.Ladings", "DeliveryGoodsPlace9", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "DeliveryGoodsDate9", c => c.DateTime(nullable: false));
            AddColumn("dbo.Ladings", "VehicleType10", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "VehicleClass10", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "VehicleNumber10", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "VehicleDriver10", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "ForwarderObservation11", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "RouteFinalDestination12", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "CustomsDeclarationNo13", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "AnnexedDocments14", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "MarksNos15", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "NoOfPackages16", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "MethodOfPacking17", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "NatureOfGoods18", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "TariffCode19_1", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "GrossWeight20_1", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "Volume21_1", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "DangerousGoodsInstructions22", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "DangerousGoodsClass22", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "DangerousGoodsCode22", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "SendersInstructions23", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "DemurrageLoading24", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "DemurrageDischarge25", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "CarriageInstructions26", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "CarriagePaid26", c => c.String(maxLength: 1));
            AddColumn("dbo.Ladings", "CarriageForward26", c => c.String(maxLength: 1));
            AddColumn("dbo.Ladings", "SpecialAgreements28", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "CachonDelivery29", c => c.String(maxLength: 255));
            DropColumn("dbo.Ladings", "PlaceOfIssue");
            DropColumn("dbo.Ladings", "DateOfIssue");
            DropColumn("dbo.Ladings", "Sender");
            DropColumn("dbo.Ladings", "SenderAddress");
            DropColumn("dbo.Ladings", "SenderPhone");
            DropColumn("dbo.Ladings", "Receiver");
            DropColumn("dbo.Ladings", "ReceiverAddress");
            DropColumn("dbo.Ladings", "ReceiverPhone");
            DropColumn("dbo.Ladings", "Carrier");
            DropColumn("dbo.Ladings", "CarrierAddress");
            DropColumn("dbo.Ladings", "CarrierPhone");
            DropColumn("dbo.Ladings", "Forwarder");
            DropColumn("dbo.Ladings", "ForwarderAddress");
            DropColumn("dbo.Ladings", "ForwarderPhone");
            DropColumn("dbo.Ladings", "TakingOverGoodsPlace");
            DropColumn("dbo.Ladings", "TakingOverGoodsDate");
            DropColumn("dbo.Ladings", "DeliveryGoodsPlace");
            DropColumn("dbo.Ladings", "DeliveryGoodsDate");
            DropColumn("dbo.Ladings", "VehicleType");
            DropColumn("dbo.Ladings", "VehicleClass");
            DropColumn("dbo.Ladings", "VehicleNumber");
            DropColumn("dbo.Ladings", "VehicleDriver");
            DropColumn("dbo.Ladings", "ForwarderObservation");
            DropColumn("dbo.Ladings", "RouteFinalDestination");
            DropColumn("dbo.Ladings", "CustomsDeclarationNo");
            DropColumn("dbo.Ladings", "AnnexedDocments");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Ladings", "AnnexedDocments", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "CustomsDeclarationNo", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "RouteFinalDestination", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "ForwarderObservation", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "VehicleDriver", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "VehicleNumber", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "VehicleClass", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "VehicleType", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "DeliveryGoodsDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Ladings", "DeliveryGoodsPlace", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "TakingOverGoodsDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Ladings", "TakingOverGoodsPlace", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "ForwarderPhone", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "ForwarderAddress", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "Forwarder", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "CarrierPhone", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "CarrierAddress", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "Carrier", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "ReceiverPhone", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "ReceiverAddress", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "Receiver", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "SenderPhone", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "SenderAddress", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "Sender", c => c.String(maxLength: 255));
            AddColumn("dbo.Ladings", "DateOfIssue", c => c.DateTime(nullable: false));
            AddColumn("dbo.Ladings", "PlaceOfIssue", c => c.String(maxLength: 255));
            DropColumn("dbo.Ladings", "CachonDelivery29");
            DropColumn("dbo.Ladings", "SpecialAgreements28");
            DropColumn("dbo.Ladings", "CarriageForward26");
            DropColumn("dbo.Ladings", "CarriagePaid26");
            DropColumn("dbo.Ladings", "CarriageInstructions26");
            DropColumn("dbo.Ladings", "DemurrageDischarge25");
            DropColumn("dbo.Ladings", "DemurrageLoading24");
            DropColumn("dbo.Ladings", "SendersInstructions23");
            DropColumn("dbo.Ladings", "DangerousGoodsCode22");
            DropColumn("dbo.Ladings", "DangerousGoodsClass22");
            DropColumn("dbo.Ladings", "DangerousGoodsInstructions22");
            DropColumn("dbo.Ladings", "Volume21_1");
            DropColumn("dbo.Ladings", "GrossWeight20_1");
            DropColumn("dbo.Ladings", "TariffCode19_1");
            DropColumn("dbo.Ladings", "NatureOfGoods18");
            DropColumn("dbo.Ladings", "MethodOfPacking17");
            DropColumn("dbo.Ladings", "NoOfPackages16");
            DropColumn("dbo.Ladings", "MarksNos15");
            DropColumn("dbo.Ladings", "AnnexedDocments14");
            DropColumn("dbo.Ladings", "CustomsDeclarationNo13");
            DropColumn("dbo.Ladings", "RouteFinalDestination12");
            DropColumn("dbo.Ladings", "ForwarderObservation11");
            DropColumn("dbo.Ladings", "VehicleDriver10");
            DropColumn("dbo.Ladings", "VehicleNumber10");
            DropColumn("dbo.Ladings", "VehicleClass10");
            DropColumn("dbo.Ladings", "VehicleType10");
            DropColumn("dbo.Ladings", "DeliveryGoodsDate9");
            DropColumn("dbo.Ladings", "DeliveryGoodsPlace9");
            DropColumn("dbo.Ladings", "TakingOverGoodsDate8");
            DropColumn("dbo.Ladings", "TakingOverGoodsPlace8");
            DropColumn("dbo.Ladings", "ForwarderPhone7");
            DropColumn("dbo.Ladings", "ForwarderAddress7");
            DropColumn("dbo.Ladings", "Forwarder7");
            DropColumn("dbo.Ladings", "CarrierPhone6");
            DropColumn("dbo.Ladings", "CarrierAddress6");
            DropColumn("dbo.Ladings", "Carrier6");
            DropColumn("dbo.Ladings", "ReceiverPhone5");
            DropColumn("dbo.Ladings", "ReceiverAddress5");
            DropColumn("dbo.Ladings", "Receiver5");
            DropColumn("dbo.Ladings", "SenderPhone4");
            DropColumn("dbo.Ladings", "SenderAddress4");
            DropColumn("dbo.Ladings", "Sender4");
            DropColumn("dbo.Ladings", "DateOfIssue3");
            DropColumn("dbo.Ladings", "PlaceOfIssue2");
        }
    }
}
